# 公共配置文件
# @author ambition
#
spring:
  application:
    name: fyzbi
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # TODO 取消注释开启分布式 session（须先配置 Redis）
    # store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  # TODO 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bi
    username: root
    password: w1VJ6kR4
    #   Redis 配置
    #   TODO 需替换配置，然后取消注释
    redis:
      database: 1
      host: localhost
      port: 6379
      timeout: 5000
    # 配置mongodb

  data:
    mongodb:
      #          uri: mongodb://账号:密码@IP:端口/数据库 用如下的配置能够成功的连接到 mongodb
      uri: mongodb://root:w1VJ6kR4@59.110.55.200:27017/?authSource=admin
#      用下面的配置 会存在权限问题
#      host: 59.110.55.200
#      port: 27017
#      username: root
#      password: w1VJ6kR4
      database: bi_database
      table: chart



  rabbitmq:
    host: 59.110.55.200
    port: 5672
    username: ambition
    password: w1VJ6kR4



    #

  #      password: 123456
  # Elasticsearch 配置
  # TODO 需替换配置，然后取消注释
  #  elasticsearch:
  #    uris: http://localhost:9200
  #    username: root
  #    password: 123456
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
server:
  address: 0.0.0.0
  port: 8101
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 微信相关
wx:
  # 微信公众平台
  # TODO 需替换配置
  mp:
    token: xxx
    aesKey: xxx
    appId: xxx
    secret: xxx
    config-storage:
      http-client-type: HttpClient
      key-prefix: wx
      redis:
        host: 127.0.0.1
        port: 6379
      type: Memory
  # 微信开放平台
  # TODO 需替换配置
  open:
    appId: xxx
    appSecret: xxx
# 对象存储
# TODO 需替换配置
cos:
  client:
    accessKey: xxx
    secretKey: xxx
    region: xxx
    bucket: xxx

yuapi:
  client:
    access-key: 2c194f2n6gp70qoe743k3gtnn40yjkqp
    secret-key: aymclodbxigfya29lb0tx8ng8u7b0ccw
